// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RentalManagementSystem.Entities;

[Index("RentalID", Name = "IX_RentalID")]
public partial class RentalPayment
{
    [Key]
    public int PaymentID { get; set; }

    public int RentalID { get; set; }

    public byte Month { get; set; }

    public int Year { get; set; }

    [Column(TypeName = "money")]
    public decimal AmountPaid { get; set; }

    public bool PaidInFull { get; set; }

    public bool RemoveFromViewFlag { get; set; }

    [ForeignKey("RentalID")]
    [InverseProperty("RentalPayments")]
    public virtual Rental Rental { get; set; }
}